# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Chapter03/object-streams" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Chapter04/file-upload" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Chapter04/server-smtp" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Chapter04/websocket-server" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Chapter08/testing-with-jest" # Location of package manifests
    schedule:
      interval: "monthly"